<a href="https://colab.research.google.com/github/IngCarlosCogua/maching_learn_ch/blob/main/Regresiones/1regresionlinealMultiple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Regreseion lineal multiple**
realizado por Ing Carlor anurlfo C

**RESTRIGCIONES!! deben satisfacerse estos 5 conseptos**

1.lINEALIDAD
2.HOMOCEDASTICIDAD
3. NORMALIDAD MULTIVARIABE
4. INDEPENDENCIA DE LOS ERRORES
5. AUSENCIA DE MULTICOLONIEALIDAD

**PASO  A PASO PARA CREAR EL MODELO **
-SELECCIONAR LAS VARIABLES CORRECTAS

-METODO ALL-IN: apostarlo todo, no es recomendable hacerlo, todas las variables son predictoras en el dataframe no se descarta ninguna 

-SELECCION HACIA ATRAS: se hace en 5 pasos , elejir nivel de sginificacion Sl = 0,05, se calcula modelo con todas las posibles variables predictoras, se elejige la variable predictora con el Pvalor mas grande, se elimina la variable predictora con pvalor mas alto, se ajusta el modelo sin dicha variable

-SELECCION HACIA ADELANTE: añadismo variables con pvalor inferior al nivel de significacion, se ajustan todos los modelos de regresionsimple con una variable, conservamos esa variable, consideramos la variable predictora con menor pvalor, fin


-ELIMINACION BIDIRECCIONAL: combina los 2 pasos en 1, se selecciona nivel se ginificaion para modelo y ptrop para ser eliminado del modelo, `se hace una seleccion asia adelante,se lleva acabo todos los pasos de eliminacion hacia atras, repetimos el cliclo, se añad la mejor variable se quitan las que sobran

-COMPARACION DE SCORES: fuerza bruta, se generan todos los metodos de regresion posibles y escojemos el que mas nos guste, no es olucion viable 10 columnas o variables de datos significan 1023 modelos para entrenar

 **texto en negrita**




# **Vamos a predecir la columna 5 el beneficio de la empresa contando con 4 variables numericas y un categorica**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


La regresion lineal multiple tiene mas variables independientes

In [2]:
#importacion de librerias
import numpy as np #calculos matematicos cientificos
import matplotlib.pyplot as plt #sublinreria para representacio  grafica
import pandas as pd # libreria para carga y manipulacion de datos
dataset = pd.read_csv('/content/drive/MyDrive/Analitica_Programadorch/Archivoscsv/50_Startups.csv')
dataset.info() #informacion de filas y columnas del dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [15]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
#X es la variable independiente predictora  y Y es la variable dependiente a predecir
#el dataset tiene 5 columnas debes tratar de que el valor a predecir este en la ultima columna para ignorarlo en X y yo Tomarlo en Y
X = dataset.iloc[:,:-1].values #iloc sirve para localizar filas i columnas por posicion,[:,:-1] toma todas las filas y todas la columnas exepto la ultima en una array
Y = dataset.iloc[:,4].values # toma todas la filas pero solo de la ultima columna

Viendo el contenido de los arrays X & Y

In [17]:
X

array([['0.0', '0.0', '1.0', '165349.2', '136897.8', '471784.1'],
       ['1.0', '0.0', '0.0', '162597.7', '151377.59', '443898.53'],
       ['0.0', '1.0', '0.0', '153441.51', '101145.55', '407934.54'],
       ['0.0', '0.0', '1.0', '144372.41', '118671.85', '383199.62'],
       ['0.0', '1.0', '0.0', '142107.34', '91391.77', '366168.42'],
       ['0.0', '0.0', '1.0', '131876.9', '99814.71', '362861.36'],
       ['1.0', '0.0', '0.0', '134615.46', '147198.87', '127716.82'],
       ['0.0', '1.0', '0.0', '130298.13', '145530.06', '323876.68'],
       ['0.0', '0.0', '1.0', '120542.52', '148718.95', '311613.29'],
       ['1.0', '0.0', '0.0', '123334.88', '108679.17', '304981.62'],
       ['0.0', '1.0', '0.0', '101913.08', '110594.11', '229160.95'],
       ['1.0', '0.0', '0.0', '100671.96', '91790.61', '249744.55'],
       ['0.0', '1.0', '0.0', '93863.75', '127320.38', '249839.44'],
       ['1.0', '0.0', '0.0', '91992.39', '135495.07', '252664.93'],
       ['0.0', '1.0', '0.0', '119943.24', '1

In [6]:
Y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

## **Tratamiendo de Datos Categoricos strings, codificacion, cardinales SI o No**

In [7]:
dataset['State'].unique() #primero identificamos los datos unicos strings de la columna 

array(['New York', 'California', 'Florida'], dtype=object)

**Recodificando los valores strings a numericos**

In [8]:
from sklearn.preprocessing import LabelEncoder  # importanto el constructor
#codificador de las variables , constructor 
LabelEncoder_X = LabelEncoder()
#damos la instruccion de que reemplace los datos de la columna dependiente en datos numericos
X[: ,3] =LabelEncoder_X.fit_transform(X[:,3])#recodifica los valores de todas las filas de la primera columna

esto a reasiganando los valores de france como un 0, spain como un 1 y germany como un 2

In [9]:
X #verificamos la variable predictora x con los valores strings convertidos en numeros

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 1],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 1],
       [100671.96, 91790.61, 249744.55, 0],
       [93863.75, 127320.38, 249839.44, 1],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 1],
       [86419.7, 153514.11, 0.0, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

# **Variables Falsas o  Dumi , recategorizar los valores de la columna string convirtiendo cada valor en columnas y validar su categorizacion con 1 y 0**

In [10]:
#librerias para decodificar los valores numericos a valores dumi
# 1 true 0 false
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
# usando el contructor columnTransformer para tranformar la columna 0 de la variable X en variable dumi columnas de unos y ceros
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [3])], remainder='passthrough')
# Entrenando y reemplazando los datos en la variable x 
X = np.array(columnTransformer.fit_transform(X), dtype = np.str)

print(X)

[['0.0' '0.0' '1.0' '165349.2' '136897.8' '471784.1']
 ['1.0' '0.0' '0.0' '162597.7' '151377.59' '443898.53']
 ['0.0' '1.0' '0.0' '153441.51' '101145.55' '407934.54']
 ['0.0' '0.0' '1.0' '144372.41' '118671.85' '383199.62']
 ['0.0' '1.0' '0.0' '142107.34' '91391.77' '366168.42']
 ['0.0' '0.0' '1.0' '131876.9' '99814.71' '362861.36']
 ['1.0' '0.0' '0.0' '134615.46' '147198.87' '127716.82']
 ['0.0' '1.0' '0.0' '130298.13' '145530.06' '323876.68']
 ['0.0' '0.0' '1.0' '120542.52' '148718.95' '311613.29']
 ['1.0' '0.0' '0.0' '123334.88' '108679.17' '304981.62']
 ['0.0' '1.0' '0.0' '101913.08' '110594.11' '229160.95']
 ['1.0' '0.0' '0.0' '100671.96' '91790.61' '249744.55']
 ['0.0' '1.0' '0.0' '93863.75' '127320.38' '249839.44']
 ['1.0' '0.0' '0.0' '91992.39' '135495.07' '252664.93']
 ['0.0' '1.0' '0.0' '119943.24' '156547.42' '256512.92']
 ['0.0' '0.0' '1.0' '114523.61' '122616.84' '261776.23']
 ['1.0' '0.0' '0.0' '78013.11' '121597.55' '264346.06']
 ['0.0' '0.0' '1.0' '94657.16' '145077.58'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


In [11]:

#etiquteando el dataset Y para predecir o respuesta con 1 y 0 original mente los valores eran si o no osea variables ordinales 
labelencoder_y = LabelEncoder()
Y = labelencoder_y.fit_transform(Y) #reasignando los valore del dataset Y
Y #imprimiendo los valores ,  los valores que antes rean si y no ahora sn¡on 1 y cero 

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# **Division de dataset Para Entrenamiento y Testeo**

del 100% de  los datos tomamos el 80 o 70 % para entrenan y el restante lo dejamos para evaluar su efectividad

In [12]:
from sklearn.model_selection import train_test_split # funcion que nos permite dividir el dataset original

Dividiendo las variables

In [13]:
#variables de entrenaiento y testeo   division de dataset , definicion de tamaño del esteo, como es una muestra de 30 valores solo por este caso ponemos 1 de cada 3 valores sera para testeo
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 1/3, random_state= 0 ) #80% de los datos o filas son para entrenaiento y 20 para testeo

Variables de testo y entrenamiento separadas 1/3 de informacion